apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mender-api-gateway
  name: mender-api-gateway
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 443
  selector:
    service: mender-api-gateway
status:
  loadBalancer: {}
