apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mender-gui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mender-gui
    spec:
      containers:
      - image: mendersoftware/gui:latest
        name: mender-gui
        resources: {}
     # restartPolicy: Always
status: {}
