apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mender-device-auth
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mender-device-auth
    spec:
      containers:
      - image: mendersoftware/deviceauth:latest
        name: mender-device-auth
        resources: {}
     # restartPolicy: OnFailure
status: {}
