apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mender-mongo-deployments
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mender-mongo-deployments
    spec:
      containers:
      - image: mongo:latest
        name: mender-mongo-deployments
        resources: {}
     # restartPolicy: Always
status: {}
