apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mender-deployments
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mender-deployments
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: minio
        - name: AWS_SECRET_ACCESS_KEY
          value: minio123
        - name: AWS_URI
          value: http://minio:9000
        image: mendersoftware/deployments:latest
        name: mender-deployments
        resources: {}
     # restartPolicy: OnFailure
status: {}
