apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: minio
  name: minio
spec:
  ports:
  - name: "9000"
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    service: minio
status:
  loadBalancer: {}
