apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: minio
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: minio
    spec:
      containers:
      - env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minio123
        image: minio/minio:RELEASE.2016-10-07T01-16-39Z
        name: minio
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
     # restartPolicy: Always
status: {}
