version: '2.1'
services:
  #
  # Setup including older clients with mender-connect
  #
  mender-client-2-5:
    # mender-connect 1.0
    image: mendersoftware/mender-client-qemu:2.5
    networks:
       - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - SERVER_URL=$SERVER_URL
      - TENANT_TOKEN=$TENANT_TOKEN
    volumes:
      # Provision demo certificate
      - ./cert/cert.crt:/mnt/config/server.crt
      # Add updated setup that puts the new demo certificate in the global ca trust store
      - ./extra/integration-testing/setup-mender-configuration.py:/setup-mender-configuration.py
