version: '2.1'
services:

    mender-api-gateway:
        ports:
            - "80:80"
        environment:
            SSL: "false"

    storage-proxy:
        volumes:
            - ./storage-proxy/no-ssl.nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

    mender-deployments:
        environment:
            DEPLOYMENTS_AWS_URI: http://s3.docker.mender.io:9000
