version: '2.1'
services:

    #
    # mender-client
    #
    mender-client:
        image: mendersoftware/mender-client-qemu:2.3.0b1
        networks:
            - mender
        stdin_open: true
        tty: true
        privileged: true
