version: '2.1'
services:

    #
    # minio
    #
    minio:
        # DO NOT upgrade this to any version "2021.05" or later.
        # We want to stay on Apache license for now.
        image: minio/minio:RELEASE.2019-04-23T23-50-36Z
        restart: on-failure
        networks:
            mender:
                aliases:
                    - minio.s3.docker.mender.io
        environment:
            MINIO_HTTP_TRACE: /dev/stdout
        command: server /export

    mender-api-gateway:
      environment:
        STORAGE_URL: ${STORAGE_URL:-s3.docker.mender.io}
      volumes:
        - ./config/traefik/traefik.minio.yaml:/etc/traefik/config/traefik.minio.yaml:ro

    #
    # mender-deployments depends on minio if minio is in use
    #
    mender-deployments:
        depends_on:
            minio:
                condition: service_healthy
