apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert -y
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mender-nats
  name: mender-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mender-nats
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert -y
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/integration-local-mender: "true"
        io.kompose.service: mender-nats
    spec:
      containers:
        - args:
            - -js
          image: nats:2.7.4-scratch
          name: mender-nats
          resources: {}
     # restartPolicy: Always
status: {}
