apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert -y
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/integration-local-mender: "true"
    io.kompose.service: mender-mongo
  name: mender-mongo
spec:
  containers:
    - image: mongo:4.4
      name: mender-mongo
      resources: {}
  restartPolicy: OnFailure
status: {}
