apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert -y
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/integration-local-mender: "true"
    io.kompose.service: mender-api-gateway
  name: mender-api-gateway
spec:
  containers:
    - args:
        - --accesslog=true
        - --entrypoints.http.address=:80
        - --entrypoints.http.http.redirections.entryPoint.scheme=https
        - --entrypoints.http.http.redirections.entryPoint.to=https
        - --entrypoints.https.address=:443
        - --entryPoints.https.transport.respondingTimeouts.idleTimeout=7200
        - --entryPoints.https.transport.respondingTimeouts.readTimeout=7200
        - --entryPoints.https.transport.respondingTimeouts.writeTimeout=7200
        - --providers.file.directory=/etc/traefik/config
      image: traefik:v2.8
      name: mender-api-gateway
      resources: {}
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: mender-api-gateway-claim0
          readOnly: true
        - mountPath: /etc/traefik/config/traefik.yaml
          name: mender-api-gateway-claim1
          readOnly: true
        - mountPath: /etc/traefik/config/traefik.middlewares.yaml
          name: mender-api-gateway-claim2
          readOnly: true
  restartPolicy: OnFailure
  volumes:
    - name: mender-api-gateway-claim0
      persistentVolumeClaim:
        claimName: mender-api-gateway-claim0
        readOnly: true
    - name: mender-api-gateway-claim1
      persistentVolumeClaim:
        claimName: mender-api-gateway-claim1
        readOnly: true
    - name: mender-api-gateway-claim2
      persistentVolumeClaim:
        claimName: mender-api-gateway-claim2
        readOnly: true
status: {}
