http:
  routers:
    minio:
      entrypoints: https
      # Use sprig flavored Go template
      rule: >-
        {{with env "STORAGE_URL" | default "s3.docker.mender.io" -}}
        Host(`{{.}}`)||Headers(`X-Forwarded-Host`,`{{.}}`) ||
        HeadersRegexp(`X-Amz-Date`, `.+`) ||
        PathPrefix(`/mender-artifact-storage`)
        {{- end}}
      tls: true
      service: minio

  services:
    minio:
      loadBalancer:
        servers:
        - url: "http://minio:9000"

