http:
  routers:
    #
    # reporting
    #
    reporting:
      entrypoints: https
      middlewares: #{{- block "circuit-breaker" . -}}{{- if not (env "TESTING") }}
      - circuit-breaker #{{- end}}{{end}}
      - userauth
      - sec-headers
      - compression
      - json-error-responder1
      - json-error-responder2
      - json-error-responder3
      - json-error-responder4
      rule: "PathPrefix(`/api/management/{version:v[0-9]+}/reporting`)"
      service: reporting
      tls: true

  services:
    reporting:
      loadBalancer:
        servers:
        - url: "http://mender-reporting:8080"
