version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /tests/requirements
    package-ecosystem: pip
    schedule:
      interval: monthly
      day: saturday
  - commit-message:
      prefix: chore
    directory: /extra/
    package-ecosystem: pip
    schedule:
      interval: monthly
      day: saturday
